name: S1GRASS_env
channels:
  - defaults
dependencies:
  - bokeh=2.1.*
  - flask=1.1.*
  - flask-sqlalchemy=2.4.*
  - gdal=3.0.2
  - numpy=1.18.*
  - pip=20.1.*
  - python=3.7.*
  - pip:
    - bootstrap-flask==1.4
    - flask-migrate==2.5.*
    - flask-table==0.5.*
    - grass-session==0.5
    - progress==1.5
    - python-dotenv==0.13.*



