"""empty message

Revision ID: 52484ca072fe
Revises: 
Create Date: 2020-05-23 20:14:16.874311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52484ca072fe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scene',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sensor', sa.String(length=3), nullable=True),
    sa.Column('orbit', sa.String(length=10), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('filepath', sa.String(length=1000), nullable=True),
    sa.Column('time_added', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scene_date'), 'scene', ['date'], unique=True)
    op.create_index(op.f('ix_scene_filepath'), 'scene', ['filepath'], unique=True)
    op.create_index(op.f('ix_scene_orbit'), 'scene', ['orbit'], unique=False)
    op.create_index(op.f('ix_scene_sensor'), 'scene', ['sensor'], unique=False)
    op.create_index(op.f('ix_scene_time_added'), 'scene', ['time_added'], unique=False)
    op.create_table('geometry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scene_id', sa.Integer(), nullable=True),
    sa.Column('columns', sa.Integer(), nullable=True),
    sa.Column('rows', sa.Integer(), nullable=True),
    sa.Column('epsg', sa.String(length=25), nullable=True),
    sa.Column('bounds_south', sa.Float(), nullable=True),
    sa.Column('bounds_north', sa.Float(), nullable=True),
    sa.Column('bounds_west', sa.Float(), nullable=True),
    sa.Column('bounds_east', sa.Float(), nullable=True),
    sa.Column('footprint', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['scene_id'], ['scene.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_geometry_epsg'), 'geometry', ['epsg'], unique=False)
    op.create_index(op.f('ix_geometry_scene_id'), 'geometry', ['scene_id'], unique=False)
    op.create_table('metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scene_id', sa.Integer(), nullable=True),
    sa.Column('acq_mode', sa.String(length=2), nullable=True),
    sa.Column('polarisation', sa.String(length=2), nullable=True),
    sa.Column('resolution', sa.Integer(), nullable=True),
    sa.Column('nodata', sa.Integer(), nullable=True),
    sa.Column('band_min', sa.Float(), nullable=True),
    sa.Column('band_max', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['scene_id'], ['scene.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metadata_acq_mode'), 'metadata', ['acq_mode'], unique=False)
    op.create_index(op.f('ix_metadata_polarisation'), 'metadata', ['polarisation'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_metadata_polarisation'), table_name='metadata')
    op.drop_index(op.f('ix_metadata_acq_mode'), table_name='metadata')
    op.drop_table('metadata')
    op.drop_index(op.f('ix_geometry_scene_id'), table_name='geometry')
    op.drop_index(op.f('ix_geometry_epsg'), table_name='geometry')
    op.drop_table('geometry')
    op.drop_index(op.f('ix_scene_time_added'), table_name='scene')
    op.drop_index(op.f('ix_scene_sensor'), table_name='scene')
    op.drop_index(op.f('ix_scene_orbit'), table_name='scene')
    op.drop_index(op.f('ix_scene_filepath'), table_name='scene')
    op.drop_index(op.f('ix_scene_date'), table_name='scene')
    op.drop_table('scene')
    # ### end Alembic commands ###
